language: php

php:
  - 5.3
  - 5.4

env:
#  - FLOW_VERSION=2.0.*
  - FLOW_VERSION=dev-master

before_script:
  - mkdir Build; cd Build
  # Install Flow in different versions
  - composer require typo3/flow:${FLOW_VERSION} --no-update
  - composer update --dev

script: phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/
